Repository Appliscale/perun, pull requests merged in 2018-04, with the labels that each got.

#105 Add --capabilities flag to perun create-stack
  README.md
  cliparser/cliparser.go
  stack/stack.go
Labels: defect, documentation, external request, user experience

#108 Update README.md
  README.md
Labels: documentation, marketing

#107 Validation of Parameters section for AWS-specific parameter types. #63 release 2.0
  offlinevalidator/offlinevalidator.go
  offlinevalidator/offlinevalidator_test.go
  offlinevalidator/template/template.go
Labels: documentation, feature, user experience

#106 Removing .preprocessed.yml #83
  .gitignore
  intrinsicsolver/fixFunctions.go
Labels: good first issue, help wanted, internals
